import = [
  "~/.config/alacritty/tokyo-night-storm.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[cursor]
style = "Beam"
vi_mode_style = "Block"

[keyboard]
bindings = [
  { key = "C", mods = "Control", action = "Copy" },
  { key = "C", mods = "Control|Shift", chars = "\u0003" },
  { key = "V", mods = "Control", action = "Paste" },
]

[window]
startup_mode = "Maximized"
dynamic_title = true
title = "Alacritty"
decorations = "Full"
padding.x = 10
padding.y = 10

[scrolling]
history = 10000
multiplier = 3

[font]
size = 14.0

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BerkeleyMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BerkeleyMono Nerd Font"
style = "Italic"

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

