source ~/.local/share/mclovin/config/bash/rc

[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh

# Habilitar auto-complete para git
if [ -f /usr/share/git/completion/git-completion.bash ]; then
  source /usr/share/git/completion/git-completion.bash
fi

# Editor used by CLI
export EDITOR="nvim"
export SUDO_EDITOR="nvim"
